echo "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" >> khdma
echo "CREATE USER IF NOT EXISTS $DB_USER@'%' IDENTIFIED BY '$DB_PASSWORD';" >> khdma
echo "GRANT ALL PRIVILEGES ON $DB_DATABASE.* TO '$DB_USER'@'%';" >> khdma
echo "FLUSH PRIVILEGES;" >> khdma